stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params: 
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/preprocessed_data
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/preprocessed_data
    - src/model/model_building.py
    params:
    - model_building.kernel
    - model_building.gamma
    - model_building.C
    - model_building.random_state
    outs:
    - model.pkl
  model_eval:
    cmd: python src/model/model_eval.py
    deps:
    - model.pkl
    - src/model/model_eval.py
    metrics:
    - metrics.json:
        cache: false